### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by marklapasa** [bat-cha/gradle-plugin-git-dependencies#20]
"To be resolved just as other dependencies, this plugin add the mavenLocal repository to your project"

Does this mean this plugin ADDS the mavenLocal repro or I need to add the mavenLocal repro to the project.

Typo? It's on the project's README.md.

Pretty awesome that this performs a checkout of a git repro. In the final step when it tries to run ./gradlew on the dependency I get this error:

C:\TestProject>gradle eclipse

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':resolveGitDependencies'.
  > java.io.IOException: Cannot run program "gradlew.bat" (in directory "C:\TestProject\build\git-dependencies\dummy-project-a"): CreateProcess error=2, The system cannot find the file specified

**Comment by bat-cha** [comment]
Hi,
it means the plugin add the mavenLocal repo to the project so you don t need to add it. regarding your error, it looks like the plugin is not able to run gradlew install on dummy project a. 
Anyway I was not able to take care of the plugin in the past few month, I ll try to give it a look and improve the way dependencies are considered. Thanks for giving me more details on what you re trying to do so that I can help
